name: Mjml CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run linting & tests
        run:  |
          yarn install
          yarn build
          yarn lint
          yarn add pkg -W
          cd packages/mjml-parser-xml
          yarn install
          yarn test --debug
          cd ../../packages/mjml-core
          yarn test --debug
          cd ../../packages/mjml
          yarn test
      
      - name: Test Linux Executable
        run: |
          mkdir -p ../../build/linux
          pkg -t node18-linux-x64 ./bin/mjml -o ../../build/linux/mjml