name: Mjml CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run linting & tests
        run:  |
          yarn install
          yarn build
          yarn lint
          cd packages/mjml-parser-xml
          yarn install
          yarn test --debug
          cd ../../packages/mjml-core
          yarn test --debug
          cd ../../packages/mjml
          yarn test
      
      - name: Build Linux Executable
        run: |
          yarn global add pkg@5.8.1
          mkdir -p ./build/linux
          pkg -t node18-linux-x64 ./packages/mjml/bin/mjml  -o ./build/linux/mjml

      - name: Build Windows Executable
        run: |
          yarn global add pkg
          mkdir -p ./build/windows
          pkg -t node18-win-x64 ./packages/mjml/bin/mjml  -o ./build/windows/mjml

      - name: Build macOS Executable
        run: |
          yarn global add pkg
          mkdir -p ./build/macos
          pkg -t node18-macos-x64 ./packages/mjml/bin/mjml  -o ./build/macos/mjml
    
      - name: Upload all Executables
        uses: actions/upload-artifact@v4
        with:
          name: Upload Artifacts
          path: ./build/*